version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:eu-central-1:139878221908:task-definition/estore-eureka-server-task:8"
        LoadBalancerInfo:
          ContainerName: "estore-eureka-server-container"
          ContainerPort: 8761